### ISSUE TITLE
Frigate Card Not Found error on some devices

### ISSUE THREAD

**Issue by tbrausch** [dermotduffy/frigate-hass-card#485]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser
Yes
**Release with the issue:**

**Last working release (if known):**
I believe it still worked with V3.0 RC1
**Browser and Operating System:**
Chrome on WIndows 11

**Description of problem:**
When frigate detects an object, I display the camera feed on a Google Nest Home device.  The following is my lovelace card config:

```
  - type: "custom:frigate-card"
    cameras:
     - camera_name: sideyard
        title: Front Yard
        live_provider: frigate-jsmpeg
```

I would like to use webrtc, but this has not worked for awhile.  Since then I switched to frigate-jsmpeg which only lagged webrtc by a couple seconds and has been working for a couple months now.  Since I updated to the latest release, however, I now get an error on the Google Display saying  "Custom Element doesn't exist: frigate-card".  The files exist in the correct directories, so not sure what is going on.  The view displays correctly in a browser.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by dermotduffy** [comment]
> I would like to use webrtc, but this has not worked for awhile. 

(Is this a problem with the card, or with WebRTC -- if the card, please file a bug, WebRTC is working just fine for me)

> "Custom Element doesn't exist: frigate-card"

This suggests the card is not installed. If you can get to the Javascript console on the Nest device (??), look out for a `FRIGATE-HASS-CARD` version number printed there. The files being in the right place is not sufficient, when you go

 * [Three dots] -> Edit Dashboard -> [Three dots] -> Manage Resources

... do you see the Frigate card JS file listed there?

**Comment by l33tconsultant** [comment]
I have the same problem viewing from Samsung family hub.  worked b4 the update, now get: Custom Element doesn't exist: frigate-card.  For what ever reason, it cant see the card.  all my pc's, androids, and everything else have no problem.  I can view all past video fine by going to media folder.

**Comment by dermotduffy** [comment]
That's very strange. Do you know what version you were on before the "update"?

**Comment by l33tconsultant** [comment]
Sorry I don't.  probably the latest stable? 2.1? So I just downgraded to 2.1 and added a new firgate card, and that worked on the Samsung.  So I re-upgraded to 3.0 and upgraded the card, same issues.

Javascript console?  No, it's just "internet" browser.  I can turn on/off js (on), block popups, or run desktop version.  All toggles have the same result: Custom Element doesn't exist: frigate-card

Adding a picture card/webrtc , with on onvif stream works.

**Comment by dermotduffy** [comment]
@tbrausch You believed it still worked with v3.0.0.rc-1 ? Do either of you have a way to verify that? (I'd also be curious if v3.0.0-rc.2 worked). If we can narrow down the version range as much as possible, I can look through the commits and try to come up with a theory...

Sounds like for both of you PC & Android is fine, but the "hub" type devices (??) have the problem only.

**Comment by l33tconsultant** [comment]
Confirm, rc-1 works.  rc-2 did not.

the family hub runs the same os as their TV's, but I would bet (not confirmed) that Amazon firetv browser would have the same issue.  different branding, same basic browser as google as Samsung.

**Comment by dermotduffy** [comment]
OK -- so that means the issue is in this sea of 157 commits: https://github.com/dermotduffy/frigate-hass-card/compare/v3.0.0-rc.1...v3.0.0-rc.2

**Comment by dermotduffy** [comment]
Without further logging information, or without someone with development experience who can reproduce the problem (e.g. to repeatedly run `git bisect`, do a build and see if we can find where it breaks) it's going to be challenging to figure this out I fear.

**Comment by dermotduffy** [comment]
Actually, I have access to a Samsung TV -- @l33tconsultant does this work if you try to open HA on the TV itself via its browser?

**Comment by l33tconsultant** [comment]
Confirmed.  It doesn't work on samsung tv internet browser, and fails with the same error.  Custom Element doesn't exist: frigate-card

**Comment by tbrausch** [comment]
Yes, I can verify that RC1 still works.

**Comment by tbrausch** [comment]
> > I would like to use webrtc, but this has not worked for awhile.
> 
> (Is this a problem with the card, or with WebRTC -- if the card, please file a bug, WebRTC is working just fine for me)
> 
I believe not being able to cast WebRTC is a problem with the Google Nest Hub.  This worked in the past, but I believe it is associated with the Hub's recent update to the new Fuchsia OS on the device.  When casting WebRTC, I get a "snapshot" of the camera displayed on the hub with all the appropriate video controls, but no video.

**Comment by oyvindhauge** [comment]
Frist of all, thank you @dermotduffy for you effort in making this excellent card!

Second, I do not know if this is relevant. However, I have the same issue as described above on Google Nest Home 7". I am pretty sure it started as soon as I upgraded to 3.0.0, and I am also pretty sure I did not try any of the release candidates. 

The card works all the time (as far as I can see) on Android, most of the time on Windows (it has been stuck loading a few times) and not that much on Ubuntu. On Ubuntu with Chrome in kiosk mode, I get the following error message "_Cannot autodetect Frigate camera name, you need to either set camera_entity and /or frigate.camera_name_". I have most certainly set camera_entity (see below). I am able to see all the cameras in the Frigate user interface as expected. I am however not able to open the camera in the entities view in Home Assisstant.

![front_door](https://user-images.githubusercontent.com/288557/160276521-61e79d52-bcc8-4bd9-8988-b920bc1ee3f9.png)

If there is something I could do to help, I would be more than happy. As I relatively recently updatet to Frigate 0.10.1 I cannot exclude this a contributing factor to my issues. However, I believe the Lovelace card worked after the upgrade of Frigate to 0.10.1 and before I upgraded the card to 3.0.0.

```
type: custom:frigate-card
live:
  preload: true
  lazy_load: true
cameras:
  - camera_entity: camera.front_door_frigate
    live_provider: frigate-jsmpeg
```

**Comment by dermotduffy** [comment]
@oyvindhauge I think you may have multiple issues mixed together. If you cannot see the video stream in HA itself (separate from the card), then your issue is with HA or the integration, not the card. The [integration](https://github.com/blakeblackshear/frigate-hass-integration) would be the right place to file a bug or seek support for that.

With that said, sounds like you are _also_ experiencing the "Frigate Card Not Found" issue on "hub" devices -- so lets keep this issue focused on that one.

[Still haven't found the time to experiment with this on a Samsung TV, I'm hoping that can let me replicate the issue and bisect the 157 commits ...]

**Comment by dermotduffy** [comment]
Update:

* I could not even get my Samsung TV browser to load the HA interface at all, it just hangs (i.e. didn't even get to where the card would load).
* Tried Samsung browser on a tablet -- works fine.

So ... have not yet found a way to test for this.

**Comment by oyvindhauge** [comment]
I am trying to help figuring this out, unfortunately without success. Hopefully, someone can aid as I am more than happy to test further.

Fist, I have still not found a way to get logging information out of the Google Nest Home.

Second, I am able to use git bisect. However, I am struggling with forcing the browser (both on the PC and probably on the Google Nest Home) to use the build/version of frigate-hass-card I want, probably due to some caching in both Chrome and on the Google Nest Home, or maybe I need to refresh something in Home Assistant? Does anyone have any tips here besides restart Home Assistant, reload resources in Home Assistant, hard reload and delete cache in Chrome? It kind of seems stuck at providing the same 3.0.0-version/file. I feel like I am missing something silly.

I did the following to run bisect. I am running Home Assistant supervised on an Ubuntu machine.
```
git clone https://github.com/dermotduffy/frigate-hass-card
git bisect start
git bisect good 85a6d23
git bisect bad 07b7c7d
npm install
npm run build
cp frigate-hass-card.js /usr/share/hassio/homeassistant/www/community/frigate-hass-card/
```

- Restart and reload resources in Home Assistant
- Test casting dashboard to the Google Nest Home (unfortunately with the same error: _custom element does not exist_)

```
git bisect bad
```
I have even reinstalled the 2.1 version of the card but I have the same problem, probably due to caching of the 3.0.0-version as mentioned above.

**Comment by dermotduffy** [comment]
**Update**: Made progress on this. Purchased a Nest hub, got [Chrome remote debugging](https://developers.google.com/cast/docs/debugging/remote_debugger) working with Home Assistant casting (future reference: requires building a local version of the [cast receiver application](https://github.com/home-assistant/frontend/tree/dev/cast) so you can match the application ID used in the receiver application with the same id you associate with your own personal Chromecast device -- via the Chromecast Developer Console). All in all, a many step process to get remote debugging working, but without it would be very hard to track down the problem.

The culprit is indeed between the range we were suspecting, it's the very harmless looking: https://github.com/dermotduffy/frigate-hass-card/pull/373

```ts
  if (!lang) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const hass = (document.querySelector('home-assistant') as any)?.hass;
    lang = hass.selectedLanguage || hass.language;
  }
```

In the above -- on the Chromecast device only -- `hass` ends up undefined, which causes the `hass.selectedLanguage` to throw an error. Since localization is used everywhere, this immediately kills the card.

So a fairly easy fix. I'm going to have to find another way to get the hass object though if I want to keep translations (which I do) -- so I'll spend a little time experimenting.

I also found a few other problems with the card on cast which I'll need to work on. I also learned (but some of you likely knew) that video using the `streaming` component is just plain not supported by HA casting at the moment ([source](https://cast.home-assistant.io/faq.html)).

**Comment by dermotduffy** [comment]
I'm going to count this as fixed (fix will be in v4.0.0 release that I'm working on now). I still find the Chromecast experience poor, but I'm tracking that as a separate issue (https://github.com/dermotduffy/frigate-hass-card/issues/570) since at least the card loads and is semi-functional.

**Comment by TheQue42** [comment]
I've managed to get the same problem on my LG webos TV. Is there anything I can do to supply additional information for debugging?

**Comment by dermotduffy** [comment]
Assuming you are not using a version of the card you built yourself, just wait for v4 (very soon I hope!) and try then. I consider this issue resolved in the code (so no extra debug info is necessary), just not yet released in a public build.

**Comment by atv2016** [comment]
Is this still considered fixed? Because i get this issue om samsung family hub as well/still.

**Comment by TheQue42** [comment]
I still have the same problem as well, on my LG WebOSTv,and I am of course running the last version.

**Comment by iMarvinS** [comment]
I  have encountered the same problem on a iPad Mini 2 running iOS 12.5.  
Version 4.0.0 of the card doesn't seem to be loaded properly. On the device it says "Custom Element doesn't exist: frigate-card".

The following output can be seen in the Web Inspector:

![image](https://user-images.githubusercontent.com/7142039/204054073-122b3748-e47d-4986-ae97-c3f3bb9ecdd0.png)

**Comment by superdong69** [comment]
Any fix on this?

**Comment by l33tconsultant** [comment]
Logger: frontend.js.latest.202304061
Source: components/system_log/__init__.py:257
First occurred: 6:16:13 AM (9 occurrences)
Last logged: 11:47:31 AM

http://hass.fubar.lcl:8123/hacsfiles/frigate-hass-card/card-b71c94d3.js:75:3295 Uncaught SyntaxError: Unexpected token .

It's been awhile, and I have used the webrtc card because it just worked.  Went back and looked and I'm still getting the custom card not found.  but this is what is being logged on home assistant (2023.4.1)
![PXL_20230407_175707484 MP](https://user-images.githubusercontent.com/5396850/230655496-1a330070-4924-4c2e-af87-a25f52f24a7d.jpg)
