### ISSUE TITLE
Process Is Undefined in release-4.0.0

### ISSUE THREAD

**Issue by NickM-27** [dermotduffy/frigate-hass-card#531]
Trying to load up the latest release-4.0.0 for testing and I am getting:

`hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=394082552308:17952:17 Uncaught ReferenceError: process is not defined`

from HomeAssistant logs and "custom:frigate-card" is unavialable. Unfortunately it doesn't seem to direct to a line or anything but I will see what else I can dig up.

**Comment by NickM-27** [comment]
Looks like it is keying on to `var __DEV__$1 = process.env.NODE_ENV !== 'production';`

**Comment by NickM-27** [comment]
removing that fixed the issue

**Comment by dermotduffy** [comment]
I have not seen that before, but did spot a related comment-o in the rollup configuration which is fixed in the PR above. Maybe see if that helps?

**Comment by NickM-27** [comment]
> I have not seen that before, but did spot a related comment-o in the rollup configuration which is fixed in the PR above. Maybe see if that helps?

unfortunately still seeing it :/

`/hacsfiles/frigate-hass-card/frigate-hass-card.js?hacstag=39408255288892:563:17448 Uncaught ReferenceError: process is not defined`

**Comment by dermotduffy** [comment]
Fixed in https://github.com/dermotduffy/frigate-hass-card/pull/543 .
